0501_1000.py

- Add a and b
- if __name__ == '__main__'

feat: Solve[1000]

---

dus00/0501_1000.py

- Add a and b
- if \_\_name\_\_ == '\_\_main\_\_':

feat: Solve 1000

---

sesame-leaf/2025_05/week01/0501_1271.py

I used integer division and modulation operator to solve this problem

feat: Solve 1271

---

dus00/2025_05/week01/0503_3273.py

_You are given a sequence of n distinct positive integers a₁, a₂, …, aₙ, where each aᵢ is a natural number between 1 and 1,000,000 (inclusive).
Given a natural number x, write a program that counts the number of pairs (aᵢ, aⱼ) such that aᵢ + aⱼ = x with 1 ≤ i < j ≤ n._
- Use the sys module for faster standard input
- Return the number of pairs whose sum equals target using sort + two pointers
- Sort in ascending order (O(n log n))
- Counter for pairs that satisfy the condition
- Initialize two pointers at the ends of the array
- Loop until the two pointers cross
- If the sum of the current two elements equals the target, increment the pair count
- Move the left pointer one step to the right
- Move the right pointer one step to the left (prevents reusing the same element)
- If the sum is …

feat: Solve 3273

---

dus00/2025_05/week02/0504_2439.py

_Print a pattern of stars as follows: the first line should contain one star, the second line two stars, and the N‑th line N stars, all right‑aligned (see the example for reference)._
- Receive the height of the triangle as input.
- Iterate from 1 to a and print each line.
- Print (a − i) spaces on the left to create right‑alignment,
- then print i ‘*’ characters to form a staircase star pattern.
- Execute the following block only when this file is run directly, not when imported as a module.

feat: Solve 2439

---

sesame-leaf/2025_05/week01/0501_1271.py
sesame-leaf/2025_05/week01/0502_11866.py
sesame-leaf/2025_05/week01/0503_16165.py
sesame-leaf/2025_05/week02/0504_2839.py
sesame-leaf/2025_05/week02/0505_2108.py

Problem 11866
I used modulation operation to make Circular Permutation
Problem 16165
I made two dictionaries. Each have Key for group name, member name, and Value for member name, group name.
This structure can easily search group to member and member to group.
Problem 2839
It's just Greedy Algorythm. So easy.
Problem 2108
I just calculated each values and printed it.

feat: Slove 11866, 16165, 2839, 2108

---

dus00/2025_05/week02/0505_11021.py

_Write a program that reads two integers, A and B, and outputs A + B._
- Read the number of test cases as an integer from the first line.
- Iterate from 1 to t, processing each case.
- Read two integers separated by whitespace on the same line and store them in a and b.
- Print the sum of the two numbers in the format Case #<number>: <result>.
- Execute the following code only when the current file is run as a script.
- Call the main function.

feat: Solve 11021

---

kimgm1001/2025_05/week02/0506_1546.py

1. Input the number of subjects as 'n'.
2. Input the scores, store them in a 'list', and assign the highest value among the elements to 'm'.
3. For each score, calculate 'score / m * 100'. Although you could average these individually transformed scores, you can also calculate the result using the formula '(sum(score) / m * 100) / n', which yields the same result.

feat: Solve 1546

---

sesame-leaf/2025_05/week02/0507_1929.py

I made is_prime() function to get prime numbers.
I thought Trial Division with prime caching is faster than using is_prime(). But it was not.

feat: Solve 1929

---

kimgm1001/2025_05/week02/0505_25206.py

This problem involves reading information for 20 major courses and calculating the GPA (Grade Point Average). Each course includes a course name, credit value, and grade (e.g., A+, A0, B+, B0). The grade is converted to a numeric value (grade point), which is multiplied by the credit to get a weighted score. The final GPA is obtained by dividing the total weighted score by the total number of credits. Note that courses with a grade of 'P' (Pass) are excluded from the GPA calculation.
1. Receive input values a, b, and c, representing the course name, credit, and grade respectively.
2. If the grade is 'P', skip the course. Otherwise, assign a numeric grade point based on the grade.
3. Add the product of credit and grade point to score1, which accumulates the total weighted score.
4. Add the …

feat: Solve 25206

---

kimgm1001/2025_05/week02/0507_2444.py

**This is a simple output problem where you print a diamond-shaped star pattern based on a given natural number n. The pattern has a symmetrical structure, with stars increasing toward the center and then decreasing, forming a diamond shape. The total number of lines is n + (n - 1).**
A natural number n is taken as input from the user.
- Use a loop where i goes from 1 to n.
- For each line:
- Print (n - i) spaces.
- Then print (2 * i - 1) stars.
- Use a loop where j goes from 1 to n - 1.
- For each line:
-  Print j spaces.
- Then print (2 * (n - j) - 1) stars.

feat: Solve 2444

---

sesame-leaf/2025_05/week02/0508_5525.py

I used the concept of Sliding Window.

feat: Solve 5525

---

dus00/2025_05/week02/0508_2581.py

_Write a program that, given two natural numbers M and N, finds all prime numbers between M and N (inclusive), and calculates both the sum of these primes and the smallest prime number among them. For example, if M = 60 and N = 100, the prime numbers between 60 and 100 are: 61, 67, 71, 73, 79, 83, 89, and 97 — a total of 8 primes. The sum of these primes is 620, and the smallest is 61._
- Read the starting value of the range
- Read the ending value of the range
- Generate a list of prime numbers in the given range [start, end]
- A number n is prime if n > 1 and has no divisors other than 1 and itself
- We only check divisibility up to the square root of n for efficiency
- If there are any prime numbers, print their sum
- Print the smallest prime number
- If there are no prime numbers in …

feat: Solve 2581

---

dus00/2025_05/week02/0509_2798.py

_The rules of Blackjack, the most popular game in the casino, are quite simple. It’s a game where players try to get the highest possible total without exceeding 21. However, Blackjack can have various rules depending on the casino. Kim Jeongin, Korea’s top Blackjack expert, has created a new version of the game to play with Sanggeun and Changyoung. In Kim Jeongin’s version of Blackjack, each card has a positive integer written on it. The dealer lays all N cards face up on the table. Then, the dealer loudly calls out a number M. Now, within a limited time, the player must choose three cards from the N cards. Because this is a modified version of Blackjack, the sum of the selected cards must be as close as possible to M, without exceeding it. Given the numbers on the N cards, write a …

feat: Solve 2798

---

sesame-leaf/2025_05/week02/0509_28702.py

The key of this problem is that there is no continuous three integers that divided into 3, 5, 15.

feat: Solve 28702

---

sesame-leaf/2025_05/week02/0510_1676.py

I factorize by 2, 5 and count. The min(count_of_2, count_of_5) is count of zeros of last digits.

feat: Solve 1676

---

dus00/2025_05/week02/0510_2588.py

- Read the first integer (multiplicand)
- Read the second number as a string so we can access individual digits
- Loop over the last three characters of b in reverse order (units → hundreds)
- Multiply a by each digit (converted back to int) and print the partial product
- Finally, multiply a by the entire number b (converted to int) and print the result
- Entry point of the script

feat: Solve 2588

---

dus00/2025_05/week03/0511_1018.py

_Seo‑jun is once again serving as the teaching assistant for the asymptotic‑notation class.
To see whether the students have grasped the material his father taught, let’s test them with the following problem._
- a1 : int — coefficient of n in f(n) = a1 × n + a0
- a0 : int — constant term of f(n)
- c : int — constant multiplier in the upper‑bound function g(n) = c × n
- n0 : int — starting value of n for the check
- int — 1 if the inequality holds for every n from n0 to 100, otherwise 0
- Read input values, invoke the check, and print the result.
- Read a1 and a0 from the first line (two integers separated by a space).
- Read c from the second line.
- Read n0 from the third line.
- Perform the check and output the result

feat: Solve 24313

---

sesame-leaf/2025_05/week03/0511_2751.c

I build Heap Sort with C because solving this problem with Python is too simple. I learnt the way to make Binary tree with array.
parent_index * 2, (parent_index * 2) + 1 is the index of child and child_index / 2 is the index of parent.

feat: Solve 2751

---

dus00/2025_05/week03/0512_2231.py

_Given a natural number N, its decomposition sum is defined as the sum of N and the sum of its digits. If a natural number M has a decomposition sum equal to N, then M is called a generator of N. For example, the decomposition sum of 245 is 256 (= 245 + 2 + 4 + 5). Therefore, 245 is a generator of 256. Of course, some natural numbers may have no generators. On the other hand, some may have multiple generators. Write a program that finds the smallest generator of a given natural number N._
- Read the input number N
- Check all numbers from 1 to N
- Start with the number itself
- Copy of the number for digit sum calculation
- Add the last digit to the sum
- Remove the last digit
- If the decomposition sum equals N
- Print the current number i (the smallest generator)
- Exit the loop as we …

feat: Solve 2231

---

kimgm1001/2025_05/week02/0510_2738.py
kimgm1001/2025_05/week03/0511_3273.py
kimgm1001/2025_05/week03/0512_2566.py

1. Read integers n and m.
2. For n lines, read each row of matrix A and store all the values into a flat list lst1.
3. Repeat the same for matrix B, storing the values into lst2.
4. Add the corresponding elements of lst1 and lst2, and store the results back into lst1.
5. Split lst1 into chunks of m elements and print each chunk as a row.
1. Import the sys module to use sys.stdin for faster input reading and read the number of elements in the list
2. Read the list, convert to integers, and sort it
3. Read the target sum value
4. Initialize a counter for the number of valid pairs and two pointers: one at the start and one at the end of the list
5. Calculate the sum of the two pointed values
6. If the sum matches the target
-Increment the count and move the left pointer to the right, right …

feat: Solve 2738, 3273, 2566

---

dus00/2025_05/week03/0513_10807.py

_Write a program that counts how many times the integer v appears among N given integers._
- Read the number of integers and convert it to an integer
- Read a line of space-separated integers and convert it to a list of integers
- Read the target integer to count
- Count how many times v appears in the list m
- Print the count

feat: Solve 10807

---

dus00/2025_05/week03/0514_25314.py

_Today is Hye-ah’s interview day. After studying hard and answering the earlier questions well, she was finally given a problem to code on the blackboard. The task was simply to add two numbers. Having read her C++ book diligently, Hye-ah wrote a straightforward function to sum two integers on the board. The interviewer looked at her code and asked, “Suppose the input and output are N-byte integers—how would you implement this program?” Hye-ah remembered what the book said about integer types: that a long int can store up to a 4-byte integer, and a long long int can store up to an 8-byte integer. She thought, “Each extra long in front of int must add another 4 bytes of storage. So long long long int would be a 12-byte integer type, and long long long long int a 16-byte type!” With the …

feat: Solve 25314

---

kimgm1001/2025_05/week03/0513_2720.py
kimgm1001/2025_05/week03/0514_1085.py
kimgm1001/2025_05/week03/0515_2231.py

1. The number of test cases t is given.
2. For each test case, an amount price (in cents) is entered.
3. For each price, divide the value by each coin denomination in order:
-Calculate how many coins of that type are needed using integer division.
-Update the remaining price using the remainder.
4. Output the number of coins for each denomination, separated by spaces.
1. Receive input values for x, y, w, and h.
2. Calculate the minimum of the horizontal distances: x and w - x.
3. Calculate the minimum of the vertical distances: y and h - y.
4. Find and print the smaller of the two minimum distances.
1. Input the value of n.
2. Since the maximum possible digit sum for a 6-digit number is 6×9=54, set the starting point i as the greater of 0 and n - 54.
3. For each number i from the starting …

feat: Solve 2720, 1085, 2231

---

dus00/2025_05/week03/0515_15552.py

_Before you dive into solving for-loop problems in earnest, keep one caution in mind: if your I/O method is slow, reading or writing multiple lines can trigger a time-limit error. C++ If you’re using cin/cout, apply both cin.tie(nullptr) andios::sync_with_stdio(false), and use the newline character (\n) instead of endl. Note: Once you do this, you must not mix in C-style I/O functions such as scanf, printf, puts, getchar, or putchar. Java Instead of Scanner and System.out.println, use BufferedReader and BufferedWriter. You only need to call BufferedWriter.flush() once at the very end.
Python Use sys.stdin.readline instead of input. Because this method keeps the trailing newline, add .rstrip() if you need to store the line as a clean string. Since input and output streams are independent, …

feat: Solve 15552

---

sesame-leaf/2025_05/week03/0513_1966.py

I made queue without pop() and append(). I used queue head pointer.
The way i express the empty space is change value of element to -1.

feat: Solve 1966

---

dus00/2025_05/week04/0518_1934.py

_For two natural numbers A and B, a common multiple is a natural number that is a multiple of both A and B. Among these common multiples, the smallest one is called the least common multiple (LCM). For example, the common multiples of 6 and 15 include 30, 60, 90, and so on, and the least common multiple is 30. Given two natural numbers A and B, write a program to find the least common multiple (LCM) of A and B._
- Imports the math module to use the built-in gcd function
- Defines a function named gcd that takes two arguments (a, b) — though they are not used inside
- Reads the number of test cases (T) from user input
- Repeats the following block T times
- Reads two integers from input and assigns them to a and b
- Calculates the least common multiple (LCM) using the formula: (a * b) / …

feat: Solve 1934

---

kimgm1001/2025_05/week03/0516_19532.py
kimgm1001/2025_05/week03/0517_1934.py
kimgm1001/2025_05/week04/0518_10798.py

1. It reads six integers from input representing the coefficients.
2. It brute-forces all possible integer values of 𝑥 and 𝑦 in the range −999 to 999 (inclusive).
3. It filters out the unique pair (𝑥, 𝑦) that satisfies both equations.
4. It prints the solution as x y.
1. Read the number of test cases
2. Read two natural numbers a and b 
3. Assign the larger number to m and the smaller to n
4. Use the Euclidean algorithm to find the greatest common divisor (GCD)
5. Compute and print the least common multiple (LCM)
-Formula: LCM = (a * b) / GC
1. Read 5 lines of input and store them in a list
2. Initialize an empty list to store the result characters
3. Iterate over columns (up to 15 characters, as max length of any line is 15)
4. Iterate over each of the 5 input strings (rows)
5. Check if …

feat: Solve 19532, 1934, 10798

---

kimgm1001/2025_05/week04/0520_9506.py

1. Read an integer n from the user
2. Define the initial values for a, b, and lst.
-a: used to find divisors
-b: index for formatting the output
-lst: a list to store the divisors
3. Exit the loop if the input is -1
4. Find all divisors of n from 1 to n-1
-If a is a divisor of n, add it to the list
5. If the sum of the divisors equals n, it means n is a perfect number
6. For formatting, insert '+' signs between the numbers and print them in one line
-b is incremented by 2 to insert '+' between every number
7. If n is not a perfect number, print a message saying so

feat: Solve 9506

---

sesame-leaf/2025_05/week04/0518_1654.py
sesame-leaf/2025_05/week04/0519_1012.py

Problem 1654
I used binary search to get answer.
It is easy to search particular value with binary search but range. It was hard to search answer that formed as range. 
Problem 1012
I used BFS to get answer.
I used DFS at first, but it exceeded the maximum of recursion. So i changed search algorithm from DFS to BFS.

feat: Solve 1654, 1012

---

dus00/2025_05/week03/0516_1260.py
dus00/2025_05/week03/0517_2903.py
dus00/2025_05/week04/0519_9095.py
dus00/2025_05/week04/0520_8393.py

_Write a program that prints the results of traversing a graph using both DFS (Depth-First Search) and BFS (Breadth-First Search). If there are multiple adjacent vertices that can be visited, visit the vertex with the smaller number first. Stop the traversal when there are no more vertices that can be visited. The vertex numbers range from 1 to N._
- Import deque from the collections module for efficient queue operations
- Read the number of vertices (n), edges (m), and the starting vertex (v)
- Initialize an adjacency matrix for the graph (1-based index)
- Read an edge between vertex a and vertex b
- Mark the edge from a to b
- Mark the edge from b to a (undirected graph)
- Create a visited list for DFS
- Create a visited list for BFS
- Mark the current vertex as visited
- Print the …

feat: Solve 1260, 8393, 2903, 9095

---

sesame-leaf/2025_05/week04/0520_14940.py
sesame-leaf/2025_05/week04/0521_9095.py

Problem 14940
I used BFS to solve the problem because BFS assure that visit particular vertex at minimum distance.
Problem 9095
I used DP to solve this problem. the form of DP that i used is memoization(bottom-up).

feat: Solve 14940, 9095

---

kimgm1001/2025_05/week04/0521_1003.py

_Given an integer N, write a program that calculates how many times 0 and 1 are printed when fibonacci(N) is called._
**1. Read the number of test cases**
**2. Track the maximum value of n for preprocessing**
**3. Assign values:**
-dp[0] = (1, 0), meaning when input is 0: print 1 zero and 0 one
-dp[1] = (0, 1), meaning when input is 1: print 0 zero and 1 one
**4. Store each test case input**
**5. Read all test cases and update max_n**
**6. Precompute Fibonacci counts using bottom-up dynamic programming**
-dp[i] = (number of 0s, number of 1s) called when computing fib(i)
**7. For each test case, print the result**
-unpack the list and print as two space-separated values

feat: Solve 1003

---

kimgm1001/2025_05/week04/0522_1193.py

The fractions are arranged in a zigzag order as follows:
1/1 → 1/2 → 2/1 → 3/1 → 2/2 → …
Let’s define these as the 1st, 2nd, 3rd, 4th, 5th, ... fractions respectively.
Given an integer **X**, write a program to find the **X-th fraction** in this sequence
1. Take input **x** and initialize the variable **n**
2. Accumulates diagonal levels until **x** becomes non-positive.
3. Then, recalculates the position **x** within that diagonal line.
4. Uses the diagonal number **(n + 1)** to determine the traversal direction:
- Even: numerator decreases
- Odd: numerator increases

feat: Solve 1193

---

dus00/2025_05/week04/0522_2525.py
dus00/2025_05/week04/0523_24262.py

_KOI Electronics is developing an artificial intelligence oven that makes it easy to cook healthy and delicious smoked duck. To use the AI oven, you simply place an appropriate amount of smoked duck ingredients into the oven. The AI oven will then automatically calculate the finishing time of the cooking process in minutes. Additionally, the AI oven from KOI Electronics features a digital clock on the front that displays the time when the smoked duck will be ready. Write a program that calculates the time at which the cooking will be completed, given the starting time of the cooking and the required cooking duration in minutes._
- Read the current hour and minute from input
- Read the cooking duration in minutes
- Add the full hours from the cooking time
- Add the remaining minutes from …

feat: Solve 2525, 24262

---

sesame-leaf/2025_05/week04/0523_7576.py

I used BFS to solve this problem.
I made function that execute BFS for one level of graph and the name of function is BFS_one_cycle().
I counted the times that BFS_one_cycle() had been called.

feat: Solve 7576

---

dus00/2025_05/week04/0524_28278.py

_Write a program that implements a stack to store integers and processes a series of commands given as input._
- Use faster input for large input sizes
- Read the number of commands
- Initialize an empty stack
- Read a command and strip newline
- Command: 1 X -> Push X onto the stack
- Extract and push the integer X
- Command: 2 -> Pop the top element and print it, or print -1 if stack is empty
- Command: 3 -> Print the current size of the stack
- Command: 4 -> Print 1 if the stack is empty, otherwise print 0
- Command: 5 -> Print the top element without removing it, or -1 if stack is empty

feat: Solve 28278

---

dus00/2025_05/week05/0525_10773.py

_Jaemin, the head of a club, is managing the ledger in preparation for a group dinner. Jaehyun is helping Jaemin handle the money, but unfortunately, Jaehyun is always so distracted that he frequently calls out the wrong amounts. Every time Jaehyun makes a mistake, he shouts "0", which means Jaemin should remove the most recently written number. After Jaemin has recorded all the numbers (including removals), he wants to know the total sum. Help Jaemin calculate the sum._
- Read the number of inputs
- Process each input number
- If the number is 0, remove the last number added
- Otherwise, add the number to the stack
- Print the sum of the remaining numbers in the stack

feat: Solve 10773

---

sesame-leaf/2025_05/week05/0526_10815.py

I am going to use masking to solve this problem. But this time, I used set type.

feat: Solve 10815

---

kimgm1001/2025_05/week04/0523_28278.py
kimgm1001/2025_05/week04/0524_2501.py

**feat: Solve 28278**
_Write a program that implements a stack of integers and processes the commands provided in the input._
**Import the sys module for fast input reading**
**Read the number of commands and convert to integer**
**Initialize an empty list to use as a stack**
**Loop over each command**
- Read the command line and split into parts
**Command '1': push an element onto the stack**
- Append the given value to the top of the stack
**Command '2': pop and print the top element**
If the stack is not empty
- Print the top element
- Remove the top element from the stack
If the stack is empty
- Print -1 to indicate underflow
**Command '3': print the size of the stack**
- Print the number of elements in the stack
**Command '4': check if the stack is empty**
- Print 0 if non-empty, 1 …

feat: Solve 28278, 2501
